name: glyfinder
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.14.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.3
  dio: ^4.0.0
  fpdart: ^0.0.10
  riverpod: ^0.14.0+3
  flutter_riverpod: ^0.14.0+3
  flutter_command: ^2.0.1
  functional_listener: ^2.0.2
  dynamic_cached_fonts: ^0.3.1
  logger: ^1.1.0
  gap: ^2.0.0
  hive: ^2.0.4
  hive_flutter: ^1.1.0
  equatable: ^2.0.3
  url_launcher: ^6.0.10
  jovial_svg: ^1.0.6
  flutter_markdown: ^0.6.6

dev_dependencies:
  import_sorter: ^4.6.0
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.4

flutter:
  uses-material-design: true

scripts: derry.yaml

import_sorter:
  comments: false
